### ISSUE TITLE
Use a name-only input

### ISSUE THREAD

**Issue by publictheta** [publictheta/vscode-create-project#2]
From: #1

The current prompt uses a plain text input which asks for the full path of the project. Consider using a name-only input instead (and provide a separate input for the parent directory if needed).

I understand that the current UI has a defect in that it may accidentally create a directory by entering a full path to a strange location.

[`window.showOpenDialog`] provides a more reliable and intuitive way to select a directory, but it does not have an option to allow the user to create a new directory.

[`window.showOpenDialog`]: https://code.visualstudio.com/api/references/vscode-api#window.showOpenDialog

To achieve the same functionality as the current prompt (i.e., specifying the name and parent directory), we need to use multi-step prompts, since the current VS Code API does not allow us to create a single prompt with multiple inputs.

(I'm a little hesitant to implement this because it's a bit complicated both in terms of implementation and user experience, but I think it's worth opening an issue to discuss it.)

**Comment by wmstack** [comment]
Sorry for the late reply. At the moment, I don't see very important use case for a name-only input, as the selection of the name is pre-selected in the prompt.

I think what may be more impactful is if the extension can do a prompt for the default project root if the command is run and the setting for the project folder is not configured, if it can do a prompt on the spot and save it to the user settings it would save the user a trip to the settings menu the first time the extension is run.

**Comment by publictheta** [comment]
Thank you for sharing your idea! This issue was mainly for reminder to me, so don't mind.

I encountered in fact the same issue during testing in a new environment. Your solution is very sensible and I will implement it soon.

Thank you again for all your contributions. I really appreciate it:)

**Comment by publictheta** [comment]
I close this issue as not planned for now. Please feel free to reopen this issue or create a new one if anyone comes up with any issues around this.
